language: php
php:
  - "5.5"
  - "5.6"

services: mysql

install:
  - composer self-update
  - composer install --dev --no-interaction

before_script:
  # Database
  - mysql -e 'create database brewblogger;'
  - mysql -u root -e "CREATE USER 'brewblogger'@'localhost' IDENTIFIED BY 'brewblogger'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'brewblogger'@'localhost' WITH GRANT OPTION;"
  - mysql -u root brewblogger < sql/2.3.3_new_install.sql
  - mysql -u root brewblogger -e 'UPDATE preferences SET mode=2;'

  # Update Behat Path
  - "sed -i -e 's,base_url: http://localhost/brewblogger/,base_url: http://localhost:8000/,g' behat.yml"

  # Start up the server
  - php -S localhost:8000 &
  - sleep 3

script:
  - vendor/bin/behat
#  - php vendor/bin/phpunit -c phpunit.xml.dist
